version: 2
project_name: terraform-provider-slack
builds:
  - id: provider
    main: ./
    binary: terraform-provider-slack
    ldflags:
      - -X github.com/ryanlwinters/terraform-provider-slack/provider.Version={{.Version}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
archives:
  - id: archive
    formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    cmd: gpg
    args:
      - --batch
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --pinentry-mode
      - loopback
      - --passphrase
      - "{{ .Env.GPG_PASSPHRASE }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
release:
  github:
    owner: ryanlwinters
    name: terraform-provider-slack
  prerelease: auto
changelog:
  skip: true

